import sys
import re

def time_to_ms(t):
    t = t.replace(',', '.')
    parts = re.split('[:.]', t)
    if len(parts) == 4:
        h, m, s, ms = map(int, parts)
        return ((h * 60 + m) * 60 + s) * 1000 + ms
    return 0

def ms_to_ass_time(ms):
    s, ms = divmod(ms, 1000)
    m, s = divmod(s, 60)
    h, m = divmod(m, 60)
    cs = ms // 10 # ASS uses centiseconds
    return f"{h}:{m:02}:{s:02}.{cs:02}"

def parse_srt(filename):
    try:
        with open(filename, 'r', encoding='utf-8-sig') as f:
            content = f.read()
    except UnicodeDecodeError:
        with open(filename, 'r', encoding='gbk', errors='ignore') as f:
            content = f.read()
            
    content = content.replace('\r\n', '\n')
    # Split by double newline, but be flexible with whitespace
    blocks = re.split(r'\n\s*\n', content.strip())
    subs = []
    for block in blocks:
        lines = block.strip().split('\n')
        if len(lines) >= 2:
            time_line = ""
            text_lines = []
            for line in lines:
                if '-->' in line:
                    time_line = line
                elif time_line:
                    text_lines.append(line)
            
            if time_line:
                match = re.search(r'(\d+:\d+:\d+[\.,]\d+) --> (\d+:\d+:\d+[\.,]\d+)', time_line)
                if match:
                    start = time_to_ms(match.group(1))
                    end = time_to_ms(match.group(2))
                    text = ' '.join(text_lines).strip() # Use space for single line joined text
                    if text:
                        subs.append({'start': start, 'end': end, 'text': text})
    return subs

ASS_HEADER = """[Script Info]
; Script generated by Antigravity
Title: Bilingual Subtitles
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: CN,PingFang SC,65,&H00F0F0F0,&H000000FF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,2.5,1,2,10,10,80,1
Style: JP,Hiragino Sans,45,&H0099CCDE,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,35,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

def generate_ass(jp_file, zh_file, out_file):
    print(f"Loading JP: {jp_file}...")
    jp_subs = parse_srt(jp_file)
    print(f"Loading ZH: {zh_file}...")
    zh_subs = parse_srt(zh_file)
    
    print(f"Generating bilingual ASS with fixed translations and dancing snippets...")
    
    # 1. Match JP snippets to best ZH
    matched_data = []
    for jp in jp_subs:
        best_overlap = 0
        best_zh = None
        for zh in zh_subs:
            o_start = max(jp['start'], zh['start'])
            o_end = min(jp['end'], zh['end'])
            overlap = o_end - o_start
            if overlap > best_overlap:
                best_overlap = overlap
                best_zh = zh
        
        if best_overlap > 100:
            matched_data.append({'jp': jp, 'zh_text': best_zh['text']})
        else:
            matched_data.append({'jp': jp, 'zh_text': None})

    # 2. Group for static Chinese lines
    # We find contiguous segments sharing the same zh_text
    zh_static_lines = []
    if matched_data:
        i = 0
        while i < len(matched_data):
            current_zh = matched_data[i]['zh_text']
            if current_zh is None:
                i += 1
                continue
            
            start_ms = matched_data[i]['jp']['start']
            end_ms = matched_data[i]['jp']['end']
            
            j = i + 1
            while j < len(matched_data) and matched_data[j]['zh_text'] == current_zh:
                end_ms = matched_data[j]['jp']['end']
                j += 1
            
            zh_static_lines.append({
                'start': start_ms,
                'end': end_ms,
                'text': current_zh
            })
            i = j

    with open(out_file, 'w', encoding='utf-8') as f:
        f.write(ASS_HEADER)
        
        # Stream 1: Static Chinese translations (Layer 0)
        # These span across multiple JP segments
        for line in zh_static_lines:
            f.write(f"Dialogue: 0,{ms_to_ass_time(line['start'])},{ms_to_ass_time(line['end'])},CN,,0,0,0,,{line['text']}\n")
            
        # Stream 2: Dancing Japanese snippets (Layer 1)
        # These follow the original JP timing
        for item in matched_data:
            jp = item['jp']
            f.write(f"Dialogue: 1,{ms_to_ass_time(jp['start'])},{ms_to_ass_time(jp['end'])},JP,,0,0,0,,{jp['text']}\n")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python srt_to_ass.py <jp.srt> <zh.srt>")
    else:
        jp_file = sys.argv[1]
        zh_file = sys.argv[2]
        # Use simple basename logic, but try to handle long filenames correctly
        basename = jp_file.rsplit('.', 1)[0]
        # If the input was already "_cleaned", we might want to strip that for the final name, 
        # but the user said "original filename_chs-jpn". 
        # For now, let's just append to whatever the first arg is.
        output_file = f"{basename}_chs-jpn.ass"
        generate_ass(jp_file, zh_file, output_file)
